# permissions for end users to view airplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airplane-viewer-role
rules:
- apiGroups:
  - play.github.com
  resources:
  - airplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - play.github.com
  resources:
  - airplanes/status
  verbs:
  - get
