# permissions for end users to edit airplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airplane-editor-role
rules:
- apiGroups:
  - play.github.com
  resources:
  - airplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - play.github.com
  resources:
  - airplanes/status
  verbs:
  - get
