# permissions for end users to view pedals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pedals-viewer-role
rules:
- apiGroups:
  - play.github.com
  resources:
  - pedals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - play.github.com
  resources:
  - pedals/status
  verbs:
  - get
