# permissions for end users to view rudders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rudder-viewer-role
rules:
- apiGroups:
  - play.github.com
  resources:
  - rudders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - play.github.com
  resources:
  - rudders/status
  verbs:
  - get
