# permissions for end users to edit rudders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rudder-editor-role
rules:
- apiGroups:
  - play.github.com
  resources:
  - rudders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - play.github.com
  resources:
  - rudders/status
  verbs:
  - get
